version: '3.3'
services:
    ewpe-smart-mqtt:
        network_mode: host
        environment:
            - 'MQTT_SERVER=mqtt://192.168.1.53'
            - MQTT_BASE_TOPIC=ewpe-smart
            - NETWORK=192.168.1.255
            - DEVICE_POLL_INTERVAL=5000
        container_name: ewpe-smart-mqtt
        build: .